version: '3.8'

services:
  backend-app:
    build: backend
    command: uvicorn app.app:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - local/.env

  frontend:
    build: frontend
    depends_on:
      - backend
    volumes:
      - ./frontend/src/:/frontend/src
      - ./frontend/public/:/frontend/public
    environment:
      - local/.env

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - local/.env
    ports:
      - 5432:5432

volumes:
  postgres_data:
